# Generated by Django 4.0.4 on 2022-05-31 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_orders_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='note',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
