# Generated by Django 4.0.4 on 2022-05-31 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('True', 'True'), ('False', 'False')], default=('False', 'False'), max_length=10),
        ),
    ]
