# Generated by Django 4.0.4 on 2022-05-21 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254)),
                ('keywords', models.CharField(max_length=254)),
                ('description', models.CharField(max_length=254)),
                ('company', models.CharField(max_length=254)),
                ('address', models.CharField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('fax', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('smtpserver', models.CharField(max_length=254)),
                ('smtpemail', models.EmailField(max_length=254)),
                ('smtppassword', models.CharField(max_length=254)),
                ('smtpport', models.IntegerField()),
                ('facebook', models.CharField(max_length=254)),
                ('instagram', models.CharField(max_length=254)),
                ('twitter', models.CharField(max_length=254)),
                ('aboutus', models.TextField()),
                ('contact', models.CharField(max_length=254)),
                ('references', models.TextField()),
                ('status', models.CharField(choices=[('True', 'Evet'), ('False', 'Hayır')], max_length=10)),
            ],
        ),
    ]
