# Generated by Django 4.0.4 on 2022-06-02 06:59

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='aboutus',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='setting',
            name='references',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
