# Generated by Django 4.0.5 on 2022-06-02 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_alter_setting_aboutus_alter_setting_references'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='references',
            field=models.TextField(),
        ),
    ]
