# Generated by Django 4.0.5 on 2022-06-02 12:06

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_alter_setting_references'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='aboutus',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='setting',
            name='references',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
